### ISSUE TITLE
c10/cuda/CUDAGuard.h  not found ？？compilation terminated

### ISSUE THREAD

**Issue by OKhyc** [SeanNaren/warp-ctc#109]
我运行到 python setup.py install 的爆出来的 错误，怎么解决呢

**Comment by SeanNaren** [comment]
A recent commit i merged doesn't work for 1.0, will revert and create a new PR till 1.1 is stable

**Comment by SeanNaren** [comment]
Pull from master

**Comment by Adhders** [comment]
> A recent commit i merged doesn't work for 1.0, will revert and create a new PR till 1.1 is stable

same error for warp-ctc-1.1_fix

**Comment by alchemi5t** [comment]
I've pulled from master and have "ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead." now.

**Comment by SeanNaren** [comment]
@alchemi5t are you running off branch pytorch_bindings?

**Comment by alchemi5t** [comment]
@SeanNaren  No. Anyway, I needed it for running your deepspeech implementation on pytorch 1.0.1 . I just found out that I can replace warp-ctc with the torch.nn.CTCLoss. Hope that works.

**Comment by SeanNaren** [comment]
it should work if you use the branch pytorch_bindings. Just FYI as well, the torch.nn.CTCLoss is known to have a few kinks to work out, so if you start seeing weird behaviour and losses, it might be the loss function!

**Comment by alchemi5t** [comment]
@SeanNaren what do you mean by branch pytorch_bindings. I understand there's a folder named that which had the installation step, i was unable install because of "c10/cuda/CUDAGuard.h not found" error. so i skipped that and decided to use the system pytorch loss.

**Comment by rusiaaman** [comment]
> @alchemi5t are you running off branch pytorch_bindings?

I got the same error on `master` branch:
``` ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.```

On `pytorch_bindings` branch I got the original error:
``` src/binding.cpp:10:33: fatal error: c10/cuda/CUDAGuard.h: No such file or directory```

I am on pytorch 1.0.0 and CUDA 10. It works for pytorch 0.4.0 but it doesn't support CUDA 10. And Tesla T4 doesn't support below CUDA 10 (I think) so I can't downgrade. Any help? Do you have any update on torch.nn.CTCLoss, and if it works good enough for most purpose in deepspeech.pytorch?

EDIT: It worked on torch==1.1.0 but not on torch==1.0.0.

**Comment by shuaijiang** [comment]
You can try `pip install warpctc-pytorch10-cuda90==0.1.3` instead of  ` python setup.py install `
